version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: investimentos_crud
      POSTGRES_PASSWORD: 862100
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - investimentos_data:/var/lib/postgres

volumes:
  investimentos_data:
